import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
      migrations.CreateModel(name="Profile",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("role",models.CharField(choices=[("ADMIN","Admin"),("MANAGER","Manager"),("TECHNICIAN","Technician"),("CUSTOMER","Customer")],default="CUSTOMER",max_length=12)),("phone",models.CharField(blank=True,max_length=32)),("company",models.CharField(blank=True,max_length=120)),("created_at",models.DateTimeField(auto_now_add=True)),("user",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="profile",to=settings.AUTH_USER_MODEL))]),
      migrations.CreateModel(name="WorkOrder",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("title",models.CharField(max_length=180)),("description",models.TextField()),("priority",models.CharField(choices=[("LOW","Low"),("NORMAL","Normal"),("HIGH","High"),("URGENT","Urgent")],max_length=8)),("status",models.CharField(choices=[("OPEN","Open"),("ASSIGNED","Assigned"),("IN_PROGRESS","In progress"),("COMPLETED","Completed"),("CLOSED","Closed")],default="OPEN",max_length=12)),("location",models.CharField(blank=True,max_length=240)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("completed_at",models.DateTimeField(blank=True,null=True)),("closed_at",models.DateTimeField(blank=True,null=True)),("customer",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="service_requests",to=settings.AUTH_USER_MODEL)),("technician",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="assigned_work_orders",to=settings.AUTH_USER_MODEL))],options={"ordering":["-created_at"]}),
      migrations.CreateModel(name="Comment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("body",models.TextField(max_length=5000)),("is_internal",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),("author",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="work_order_comments",to=settings.AUTH_USER_MODEL)),("work_order",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="comments",to="service.workorder"))],options={"ordering":["created_at"]}),
      migrations.CreateModel(name="WorkOrderEvent",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("event_type",models.CharField(max_length=24)),("from_value",models.CharField(blank=True,max_length=180)),("to_value",models.CharField(blank=True,max_length=180)),("note",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True)),("actor",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="work_order_events",to=settings.AUTH_USER_MODEL)),("work_order",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="history",to="service.workorder"))],options={"ordering":["created_at","pk"]}),
      migrations.CreateModel(name="Attachment",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("file",models.FileField(upload_to="service.models.attachment_path",validators=[django.core.validators.FileExtensionValidator(["pdf","png","jpg","jpeg","txt","docx","xlsx"]) ])),("original_name",models.CharField(max_length=255)),("uploaded_at",models.DateTimeField(auto_now_add=True)),("uploaded_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="work_order_attachments",to=settings.AUTH_USER_MODEL)),("work_order",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="attachments",to="service.workorder"))]),
      migrations.AddIndex(model_name="workorder",index=models.Index(fields=["status","priority"],name="service_wo_status_5e558a_idx")),
      migrations.AddIndex(model_name="workorder",index=models.Index(fields=["customer","created_at"],name="service_wo_custome_2ad623_idx")),
      migrations.AddIndex(model_name="workorder",index=models.Index(fields=["technician","status"],name="service_wo_technic_30fb87_idx")),
    ]
