# Generated by Django 5.2.18 on 2026-10-07 08:29

import django.core.validators
import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workorder',
            new_name='service_wor_status_f185b0_idx',
            old_name='service_wo_status_5e558a_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='service_wor_custome_bda7db_idx',
            old_name='service_wo_custome_2ad623_idx',
        ),
        migrations.RenameIndex(
            model_name='workorder',
            new_name='service_wor_technic_0af8f9_idx',
            old_name='service_wo_technic_30fb87_idx',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=service.models.attachment_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'txt', 'docx', 'xlsx'])]),
        ),
    ]
